name: eatsure_restaurant_admin
description: Admin panel for restaurant owner in eatsure
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cache_manager: ^1.0.0+4
  flutter_advanced_switch: ^3.0.1
  eva_icons_flutter: ^3.0.2
  flutter_dotenv: ^5.0.2
  persistent_bottom_nav_bar: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.4
  shimmer: ^2.0.0
  sizer: ^2.0.15
  fl_chart: ^0.63.0
  lottie: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - .env
    - assets/icons/eatsure_logo.png
    - assets/animations/loader.json

  uses-material-design: true
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
