// ignore_for_file: non_constant_identifier_names
import 'package:flutter_dotenv/flutter_dotenv.dart';

class ApiRoutes {
  //! Authentication
  String AUTHENTICATION_LOGIN = dotenv.env['AUTHENTICATION_LOGIN']!;
  String AUTHENTICATION_SIGN_UP = dotenv.env['AUTHENTICATION_SIGN_UP']!;

  //! USERS
  String USER_FETCH_ALL = dotenv.env['USER_FETCH_ALL']!;

  //! RESTAURANTS
  String RESTAURANT_FETCH_ALL = dotenv.env['RESTAURANT_FETCH_ALL']!;
  String RESTAURANT_FETCH_BY_ID = dotenv.env['RESTAURANT_FETCH_BY_ID']!;
  String RESTAURANT_REMOVE_RESTAURANT =
      dotenv.env['RESTAURANT_REMOVE_RESTAURANT']!;
  String RESTAURANT_ADD_NEW_RESTAURANT =
      dotenv.env['RESTAURANT_ADD_NEW_RESTAURANT']!;
  String RESTAURANT_FETCH_CATEGORY = dotenv.env['RESTAURANT_FETCH_CATEGORY']!;

  //! ADVERTISEMENTS
  String ADVERTISEMENT_CREATE = dotenv.env['ADVERTISEMENT_CREATE']!;
  String ADVERTISEMENT_DELETE = dotenv.env['ADVERTISEMENT_DELETE']!;
  String ADVERTISEMENT_FETCH_ALL = dotenv.env['ADVERTISEMENT_FETCH_ALL']!;

  //! ANNOUNCEMENTS
  String ANNOUNCEMENT_CREATE = dotenv.env['ANNOUNCEMENT_CREATE']!;
  String ANNOUNCEMENT_FETCH = dotenv.env['ANNOUNCEMENT_FETCH']!;
  String ANNOUNCEMENT_DELETE = dotenv.env['ANNOUNCEMENT_DELETE']!;

//! RESTAURANT MENU
  String RESTAURANT_MENU_ADD_MENU = dotenv.env['RESTAURANT_MENU_ADD_MENU']!;
  String RESTAURANT_MENU_DELETE_MENU =
      dotenv.env['RESTAURANT_MENU_DELETE_MENU']!;
  String RESTAURANT_MENU_EXISTING_ADD_ITEM =
      dotenv.env['RESTAURANT_MENU_EXISTING_ADD_ITEM']!;

//! RESTAURANT MENU ITEM
  String RESTAURANT_MENU_ITEM_ADD_ITEM =
      dotenv.env['RESTAURANT_MENU_ITEM_ADD_ITEM']!;
  String RESTAURANT_MENU_ITEM_REMOVE_ITEM =
      dotenv.env['RESTAURANT_MENU_ITEM_REMOVE_ITEM']!;

  //! RESTAURANT BANNER
  String RESTAURANT_BANNER_ADD = dotenv.env['RESTAURANT_BANNER_ADD']!;
  String RESTAURANT_BANNER_REMOVE = dotenv.env['RESTAURANT_BANNER_REMOVE']!;

  //! ORDER
  String ORDER_PLACE_ORDER = dotenv.env['ORDER_PLACE_ORDER']!;
  String ORDER_CANCEL_ORDER = dotenv.env['ORDER_CANCEL_ORDER']!;
  String ORDER_FETCH_ORDER = dotenv.env['ORDER_FETCH_ORDER']!;
}
